// // Package docs Code generated by swaggo/swag. DO NOT EDIT
// package docs

// import (
// 	"github.com/swaggo/swag"
// )

// const docTemplate = `{
//     "swagger": "2.0",
//     "info": {
//         "title": "Aviator Betting Game API",
//         "version": "1.0.0",
//         "description": "Real-time Aviator betting game backend with WebSocket support",
//         "contact": {
//             "name": "API Support",
//             "email": "support@aviator.game"
//         },
//         "license": {
//             "name": "Apache 2.0",
//             "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
//         }
//     },
//     "host": "localhost:8080",
//     "basePath": "/api/v1",
//     "schemes": ["http", "https"],
//     "consumes": ["application/json"],
//     "produces": ["application/json"],
//     "paths": {
//         "/health": {
//             "get": {
//                 "summary": "Health Check",
//                 "tags": ["Health"],
//                 "responses": {"200": {"description": "Server is healthy"}}
//             }
//         },
//         "/register": {
//             "post": {
//                 "summary": "User Registration",
//                 "tags": ["Authentication"],
//                 "responses": {"201": {"description": "User registered successfully"}}
//             }
//         },
//         "/login": {
//             "post": {
//                 "summary": "User Login",
//                 "tags": ["Authentication"],
//                 "responses": {"200": {"description": "Login successful"}}
//             }
//         },
//         "/profile": {
//             "get": {
//                 "summary": "Get User Profile",
//                 "tags": ["Profile"],
//                 "responses": {"200": {"description": "Profile retrieved successfully"}}
//             }
//         },
//         "/wallet": {
//             "get": {
//                 "summary": "Get Wallet Balance",
//                 "tags": ["Wallet"],
//                 "responses": {"200": {"description": "Wallet retrieved successfully"}}
//             }
//         },
//         "/bet": {
//             "post": {
//                 "summary": "Place a Bet",
//                 "tags": ["Betting"],
//                 "responses": {"201": {"description": "Bet placed successfully"}}
//             }
//         },
//         "/cashout": {
//             "post": {
//                 "summary": "Cashout a Bet",
//                 "tags": ["Betting"],
//                 "responses": {"200": {"description": "Cashout successful"}}
//             }
//         },
//         "/bets/history": {
//             "get": {
//                 "summary": "Get Bet History",
//                 "tags": ["Betting"],
//                 "responses": {"200": {"description": "Bet history retrieved"}}
//             }
//         },
//         "/game/history": {
//             "get": {
//                 "summary": "Get Game History",
//                 "tags": ["History"],
//                 "responses": {"200": {"description": "Game history retrieved"}}
//             }
//         },
//         "/transactions/history": {
//             "get": {
//                 "summary": "Get Transaction History",
//                 "tags": ["History"],
//                 "responses": {"200": {"description": "Transaction history retrieved"}}
//             }
//         },
//         "/ws": {
//             "get": {
//                 "summary": "WebSocket Connection",
//                 "tags": ["WebSocket"],
//                 "responses": {"101": {"description": "Switching Protocols"}}
//             }
//         }
//     }
// }`

// type swaggerInfo struct {
// 	Version     string
// 	Host        string
// 	BasePath    string
// 	Schemes     []string
// 	Title       string
// 	Description string
// }

// // SwaggerInfo holds exported Swagger Definition
// var SwaggerInfo = swaggerInfo{
// 	Version:     "1.0.0",
// 	Host:        "localhost:8080",
// 	BasePath:    "/api/v1",
// 	Schemes:     []string{"http", "https"},
// 	Title:       "Aviator Betting Game API",
// 	Description: "Real-time Aviator betting game backend with WebSocket support",
// }

// type s struct{}

// func (s *s) ReadDoc() string {
// 	return docTemplate
// }

// // SwaggerDoc represents the Swagger documentation
// type SwaggerDoc interface {
// 	ReadDoc() string
// }

// func init() {
// 	swag.Register(swag.Name, &s{})
// }

package docs

import (
	"github.com/swaggo/swag"
)

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "Aviator Betting Game API",
    "version": "1.0.0",
    "description": "Real-time Aviator betting game backend with WebSocket support",
    "contact": {
      "name": "API Support",
      "email": "support@aviator.game"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "localhost:8080",
  "basePath": "/api/v1",
  "schemes": ["http", "https"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "JWT Bearer token. Format: Bearer {token}"
    }
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "Health Check",
        "description": "Check if the server is running and healthy",
        "tags": ["Health"],
        "security": [],
        "responses": {
          "200": {
            "description": "Server is healthy",
            "schema": {
              "$ref": "#/definitions/HealthResponse"
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "summary": "Register a new user",
        "description": "Register a new user with name, email and password",
        "tags": ["Authentication"],
        "security": [],
        "parameters": [
          {
            "name": "request",
            "in": "body",
            "required": true,
            "description": "User registration data",
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User registered successfully",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "400": {
            "description": "Invalid input or validation failed",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "409": {
            "description": "Email already exists",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "User login",
        "description": "Login with email and password to get JWT token",
        "tags": ["Authentication"],
        "security": [],
        "parameters": [
          {
            "name": "request",
            "in": "body",
            "required": true,
            "description": "User login credentials",
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login successful",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "400": {
            "description": "Invalid request or validation failed",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Authentication failed",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/verify": {
      "get": {
        "summary": "Verify JWT token",
        "description": "Verify the validity of a JWT token and return user information",
        "tags": ["Authentication"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Token is valid",
            "schema": {
              "$ref": "#/definitions/VerifyTokenResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/profile": {
      "get": {
        "summary": "Get User Profile",
        "description": "Get authenticated user's profile information including wallet balance",
        "tags": ["Profile"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Profile retrieved successfully",
            "schema": {
              "$ref": "#/definitions/ProfileResponse"
            }
          },
          "401": {
            "description": "Unauthorized - Invalid or missing token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "summary": "Update User Profile",
        "description": "Update user's name and email",
        "tags": ["Profile"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "request",
            "in": "body",
            "required": true,
            "description": "Profile update data",
            "schema": {
              "$ref": "#/definitions/UpdateProfileRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Profile updated successfully",
            "schema": {
              "$ref": "#/definitions/ProfileResponse"
            }
          },
          "400": {
            "description": "Invalid request or validation failed",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/profile/statistics": {
      "get": {
        "summary": "Get User Statistics",
        "description": "Get authenticated user's game statistics",
        "tags": ["Profile"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Statistics retrieved successfully",
            "schema": {
              "$ref": "#/definitions/ProfileStatisticsResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/wallet": {
      "get": {
        "summary": "Get Wallet Balance",
        "description": "Get authenticated user's current wallet balance and transaction count",
        "tags": ["Wallet"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Wallet retrieved successfully",
            "schema": {
              "$ref": "#/definitions/WalletResponse"
            }
          },
          "401": {
            "description": "Unauthorized - Invalid or missing token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Wallet not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/bet": {
      "post": {
        "summary": "Place a Bet",
        "description": "Place a new bet on the current game round with optional auto-cashout",
        "tags": ["Betting"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "request",
            "in": "body",
            "required": true,
            "description": "Bet request data",
            "schema": {
              "$ref": "#/definitions/BetRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Bet placed successfully",
            "schema": {
              "$ref": "#/definitions/BetResponse"
            }
          },
          "400": {
            "description": "Bet placement failed - Insufficient balance or invalid amount",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized - Invalid or missing token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/cashout": {
      "post": {
        "summary": "Cashout a Bet",
        "description": "Cashout an active bet at the current multiplier value",
        "tags": ["Betting"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "request",
            "in": "body",
            "required": true,
            "description": "Cashout request data",
            "schema": {
              "$ref": "#/definitions/CashoutRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cashout successful",
            "schema": {
              "$ref": "#/definitions/CashoutResponse"
            }
          },
          "400": {
            "description": "Cashout failed - Bet not found or already cashed out",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized - Invalid or missing token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/bets/history": {
      "get": {
        "summary": "Get Bet History",
        "description": "Get user's betting history with pagination",
        "tags": ["Betting"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "type": "integer",
            "default": 1,
            "description": "Page number (1-indexed)"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "default": 10,
            "description": "Items per page"
          }
        ],
        "responses": {
          "200": {
            "description": "Bet history retrieved successfully",
            "schema": {
              "$ref": "#/definitions/BetHistoryResponse"
            }
          },
          "401": {
            "description": "Unauthorized - Invalid or missing token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/game/history": {
      "get": {
        "summary": "Get Game History",
        "description": "Get global game round history with crash multipliers and timestamps",
        "tags": ["History"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "type": "integer",
            "default": 1,
            "description": "Page number (1-indexed)"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "default": 20,
            "description": "Items per page"
          }
        ],
        "responses": {
          "200": {
            "description": "Game history retrieved successfully",
            "schema": {
              "$ref": "#/definitions/GameHistoryResponse"
            }
          },
          "401": {
            "description": "Unauthorized - Invalid or missing token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/transactions/history": {
      "get": {
        "summary": "Get Transaction History",
        "description": "Get user's transaction history",
        "tags": ["History"],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "type": "integer",
            "default": 1,
            "description": "Page number (1-indexed)"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "default": 20,
            "description": "Items per page"
          }
        ],
        "responses": {
          "200": {
            "description": "Transaction history retrieved successfully",
            "schema": {
              "$ref": "#/definitions/TransactionHistoryResponse"
            }
          },
          "401": {
            "description": "Unauthorized - Invalid or missing token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/ws": {
      "get": {
        "summary": "WebSocket Connection",
        "description": "WebSocket endpoint for real-time game events and multiplier updates",
        "tags": ["WebSocket"],
        "security": [],
        "responses": {
          "101": {
            "description": "Switching Protocols to WebSocket"
          },
          "400": {
            "description": "Invalid WebSocket upgrade request"
          }
        }
      }
    }
  },
  "definitions": {
    "HealthResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": true
        },
        "message": {
          "type": "string",
          "example": "Server is healthy"
        },
        "data": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "example": "ok"
            }
          }
        }
      }
    },
    "RegisterRequest": {
      "type": "object",
      "required": ["name", "email", "password"],
      "properties": {
        "name": {
          "type": "string",
          "example": "John Doe"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "john@example.com"
        },
        "password": {
          "type": "string",
          "example": "SecurePassword123"
        }
      }
    },
    "LoginRequest": {
      "type": "object",
      "required": ["email", "password"],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "example": "john@example.com"
        },
        "password": {
          "type": "string",
          "example": "SecurePassword123"
        }
      }
    },
    "UpdateProfileRequest": {
      "type": "object",
      "required": ["name", "email"],
      "properties": {
        "name": {
          "type": "string",
          "example": "John Doe"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "john@example.com"
        }
      }
    },
    "AuthResponse": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string",
          "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        },
        "user": {
          "$ref": "#/definitions/UserResponse"
        }
      }
    },
    "UserResponse": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "1"
        },
        "name": {
          "type": "string",
          "example": "John Doe"
        },
        "email": {
          "type": "string",
          "example": "john@example.com"
        },
        "balance": {
          "type": "number",
          "format": "double",
          "example": 1000.5
        },
        "created_at": {
          "type": "string",
          "example": "2026-04-07T10:30:00Z"
        }
      }
    },
    "VerifyTokenResponse": {
      "type": "object",
      "properties": {
        "user": {
          "$ref": "#/definitions/UserResponse"
        }
      }
    },
    "ProfileResponse": {
      "type": "object",
      "properties": {
        "user": {
          "$ref": "#/definitions/UserResponse"
        }
      }
    },
    "ProfileStatisticsResponse": {
      "type": "object",
      "properties": {
        "total_bets": {
          "type": "integer",
          "example": 25
        },
        "total_wins": {
          "type": "integer",
          "example": 12
        },
        "total_losses": {
          "type": "integer",
          "example": 13
        }
      }
    },
    "WalletResponse": {
      "type": "object",
      "properties": {
        "balance": {
          "type": "number",
          "format": "double",
          "example": 1000.5
        }
      }
    },
    "BetRequest": {
      "type": "object",
      "required": ["amount"],
      "properties": {
        "amount": {
          "type": "number",
          "format": "double",
          "example": 50
        },
        "auto_cashout": {
          "type": "number",
          "format": "double",
          "example": 2.5
        }
      }
    },
    "BetResponse": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "example": 1
        },
        "amount": {
          "type": "number",
          "format": "double",
          "example": 50
        }
      }
    },
    "CashoutRequest": {
      "type": "object",
      "required": ["bet_id"],
      "properties": {
        "bet_id": {
          "type": "integer",
          "example": 1
        }
      }
    },
    "CashoutResponse": {
      "type": "object",
      "properties": {
        "bet_id": {
          "type": "integer",
          "example": 1
        },
        "cashout_multiplier": {
          "type": "number",
          "format": "double",
          "example": 2.45
        },
        "payout": {
          "type": "number",
          "format": "double",
          "example": 122.5
        }
      }
    },
    "BetHistoryResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BetResponse"
          }
        }
      }
    },
    "GameHistoryResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    },
    "TransactionHistoryResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "example": "Error message"
        },
        "error": {
          "type": "string",
          "example": "Detailed error information"
        }
      }
    }
  },
  "tags": [
    {
      "name": "Health",
      "description": "Server health check"
    },
    {
      "name": "Authentication",
      "description": "User registration and login"
    },
    {
      "name": "Profile",
      "description": "User profile management"
    },
    {
      "name": "Wallet",
      "description": "Wallet and balance management"
    },
    {
      "name": "Betting",
      "description": "Betting operations and history"
    },
    {
      "name": "History",
      "description": "Game and transaction history"
    },
    {
      "name": "WebSocket",
      "description": "Real-time WebSocket events"
    }
  ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Definition
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "localhost:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{"http", "https"},
	Title:       "Aviator Betting Game API",
	Description: "Real-time Aviator betting game backend with WebSocket support",
}

type s struct{}

func (s *s) ReadDoc() string {
	return docTemplate
}

// SwaggerDoc represents the Swagger documentation
type SwaggerDoc interface {
	ReadDoc() string
}

func init() {
	swag.Register(swag.Name, &s{})
}
